package com.fivegoodmins.fivegoodmins.action;

public enum Region {
    BLAGOEVGRAD, BURGAS, DOBRICH, GABROVO, HASKOVO, KARDZHALI, KYUSTENDIL,
    LOVECH, MONTANA, PAZARDZHIK, PERNIK, PLEVEN, PLOVDIV, RAZGRAD, RUSE,
    SHUMEN, SILISTRA, SLIVEN, SMOLYAN, SOFIA_CITY, SOFIA_PROVINCE,
    STARA_ZAGORA, TARGOVISHTE, VARNA, VELIKO_TARNOVO, VIDIN, VRATSA, YAMBOL,
    NATIONAL, INTERNATIONAL
}
